cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

ofs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',  include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name="product_list"),
    path('department', views.department, name="department"),
    path('<str:category_slug>', views.product_list, name="product_list_by_category"),
    path('<int:id>/<str:slug>', views.product_detail, name="product_detail"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('about/', views.about, name="AboutUs"),
    path('contact/', views.contact, name="ContactUs"),
    path('tracker/', views.tracker, name="TrackingStatus"),
    path('search/', views.search, name="Search"),
    path('productview/', views.productView, name="ProductView"),
    path('checkout/', views.checkout, name="CheckOut"),

]

shop/models.py
from django.db import models
from django.urls import reverse

class user_reg(models.Model):
    user_id = models.AutoField
    fname = models.TextField('First Name', max_length=120)
    lname = models.TextField('Last Name', max_length=120)
    uname = models.TextField(max_length=120)
    contact_info = models.BigIntegerField()
    email = models.EmailField(max_length=50)
    gender = models.TextField(max_length=6)
    pwd1 = models.TextField(max_length=30)

    def __str__(self):
        return self.fname

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Subcategories(models.Model):
    Scategory = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'subcategory'
        verbose_name_plural = 'subcategories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(Subcategories, related_name='subproducts', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from . models import user_reg, Category,Product
from cart.forms import CartAddProductForm
from django.contrib import messages
from django.contrib.messages import get_messages
import re
from django.db.models import Q

# Create your views here.
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-copyZ0-9._-]+\.[a-zA-Z]+$')
CONTACT_REGEX = re.compile(r'^[0-9]')
CONTACT_REGEXX = re.compile(r'^[1-9]{1}[0-9]{9}')

def index(request):
    return render(request, 'shop/index.html')

def register(request, category_slug= None):

    if request.method == "POST":
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        uname = request.POST.get('uname')
        contact = request.POST.get('contact')
        email = request.POST.get('email')
        gender = request.POST.get('gender')
        pwd1 = request.POST.get('pwd1')
        pwd2 = request.POST.get('pwd2')

        if len(email) < 1:
            messages.add_message( request, messages.ERROR, "Email is required!")

        if not EMAIL_REGEX.match( email ):
            messages.add_message(request, messages.ERROR, "Invalid email format! Ex: test@text.com")

        if not CONTACT_REGEX.match( contact ):
            messages.add_message(request, messages.ERROR, "Invalid Contact format!!!")

        if not CONTACT_REGEXX.match( contact ):
            messages.add_message(request, messages.ERROR, "Contact must be 10 digit numbers!!!")

        if len(pwd1) < 8:
            messages.add_message(request, messages.ERROR, "Password must be between 8-32 character!")

        if pwd1 != pwd2:
            messages.add_message(request, messages.ERROR, "Password and Confirm Password must match!")

        if user_reg.objects.filter(email=email).count() > 0:
            messages.add_message(request, messages.ERROR, "A user with this email is already exists!")

        if user_reg.objects.filter(uname=uname).count() > 0:
            messages.add_message(request, messages.ERROR, "A user with this user name is already exists!")

        if len(get_messages(request)) > 0:
            msg = get_messages(request)
            return render(request, 'reg_login/register.html', {'msg': msg})

        else:

            reg1 = user_reg(fname=fname, lname=lname, uname=uname, contact_info=contact, email=email, gender=gender, pwd1=pwd1)
            reg1.save()

            category = None
            categories = Category.objects.all()
            products = Product.objects.filter(available=True)

            if category_slug:
                category = get_object_or_404(Category, slug=category_slug)
                products = products.filter(category=category)

            return render(request, 'shop/products/list.html', {'category': category,
                                                               'categories': categories,
                                                               'products': products})

    else:
        return render(request, 'reg_login/register.html')


def login(request, category_slug= None):
    username = 'not logged in'
    if request.method == "POST":

        name = request.POST.get('login_uname')
        pwd = request.POST.get('login_pwd')

        try:

            check_uname = user_reg.objects.filter(uname=request.POST['login_uname'])[0]
            check_pwd = user_reg.objects.filter(pwd1=request.POST['login_pwd'])[0]

            if name == check_uname.uname and pwd == check_pwd.pwd1:

                    username = name
                    request.session['username'] = username

                    category = None
                    categories = Category.objects.all()
                    products = Product.objects.filter(available=True)

                    if category_slug:
                        category = get_object_or_404(Category, slug=category_slug)
                        products = products.filter(category=category)


                    return render(request, 'shop/products/list.html', {'category': category,
                                                                       'categories': categories,
                                                                       'products': products,
                                                                       'username':username})

            else:
                return render(request, 'reg_login/login.html')


        except:
            messages.add_message(request, messages.ERROR, "Invalid UserName or Password !!")

            if len(get_messages(request)) > 0:
                msg = get_messages(request)
                return render(request, 'reg_login/login.html', {'msg': msg})

            return render(request, 'reg_login/login.html')

    else:
        return render(request, 'reg_login/login.html')

def logout(request, category_slug= None):
    try:
        del request.session['username']
        loggedout ='You are now logged out !'
        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        return render(request, 'shop/products/list.html', {'category': category,
                                                           'categories': categories,
                                                           'products': products,
                                                           'username': loggedout})
    except:
        pass






def product_list(request, category_slug= None):

    if request.session.has_key('username'):
        username = request.session['username']
        un = username



    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/products/list.html', {'category': category,
                                                  'categories': categories,
                                                  'products': products})



def department(request, category_slug= None):

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/products/departments.html', {'category': category,
                                                  'categories': categories,
                                                  'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    return render(request, 'shop/products/detail.html',
                  {'product': product,
                   'cart_product_form':cart_product_form})

def about(request):

    return render(request, 'shop/ExtraPages/aboutus.html')

def contact(request):

    return render(request, 'shop/ExtraPages/contactus.html')

def tracker(request):
    return HttpResponse("This is Tracker page of Shop")


def search(request, category_slug= None):
    query = request.GET.get('search')

    if request.session.has_key('username'):
        username = request.session['username']
        un = username

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(Q(name__icontains=query) | Q(price__icontains=query) | Q(description__icontains=query) )

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/ExtraPages/search.html', {'category': category,
                                                  'categories': categories,
                                                  'products': products})



def productView(request):
    return HttpResponse("This is Product View page of Shop")

def checkout(request):
    return HttpResponse("This is Check Out page of Shop")

shop/templates/shop/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Online Shop </title>

    <link rel="stylesheet" href="{% static 'reg_login_CSS/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}"/>
    <!-- fontawesome-->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>

    <title> The Furniture Shop </title>

</head>
<body>

<!-- **************   Nav Bar    *****************-->

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="#">TFS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:product_list' %}">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:department' %}">Departments</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:AboutUs' %}">About Us</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:ContactUs' %}">Contact Us</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:AboutUs' %}">Track Order</a>
              </li>



<!--              <li class="nav-item dropdown" >-->
<!--                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                  Dropdown-->
<!--                </a>-->

<!--                <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                    {% for c in categories %}-->

<!--                    <div  style=" background-color:lightgreen; padding:5px; border-radius: 0 10px; margin:2px" {% if category.slug == c.slug %}class="selected"{% endif %}>-->
<!--                        <a href="{{ c.get_absolute_url }}"  style="display: inline-block; color: black; text-decoration: none;">{{ c.name }}</a>-->
<!--                    </div>-->

<!--                    {% endfor %}-->
<!--                </div>-->

<!--              </li>-->

              <li>

              </li>
            </ul>
          </div>
        </nav>


    <div  style=" border:2px solid #343a40; border-radius:10px; color:black;">
    <div class="container" style="margin-top:50px;">
        <div class="row mt-2">
            <div class="col-lg-6 col-xs-8 col-sm-6 d-flex flex-row">
                <div class="py-2">
                    {% if username == 'You are now logged out !' %}
                        <h4>{{ username }}</h4>
                    {% elif username|length > 0 %}
                        <h4>Hello {{ username }}</h4>
                    {% else %}
                        <h4> Visitor </h4>
                    {% endif %}
                </div>

            </div>
            <div class="col-lg-6 col-xs-4 col-sm-6 d-flex flex-row-reverse">
                <ul class="my-2">
                  <b>
                      <li style="display:inline;"><a href="{% url 'shop:login' %}" style="color: black;">Login</a></li>

                      <li class="ml-3" style="display:inline;"><a href="{% url 'shop:register' %}" style="color: black;">Register</a></li>
                      <li style="display:inline;"><a href="{% url 'shop:logout' %}" style="color: black;">Logout</a></li>
                  </b>
                </ul>
            </div>
        </div>
    </div>
        </div>

<!-- **************   Brand name    *****************-->

    <div class="container">
        <div class="row my-3">
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <img src="{% static 'logos/main.png' %}" class="img-fluid" alt="Responsive image">
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 d-flex flex-row-reverse">

                <div class="my-2">
                    <ul>
                        <li style="display:inline;">
                            <div>
                                {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                <div style=" height:40px; width:65px;">
                                    <a href="{% url 'cart:cart_detail' %}">
                                        <div class="d-flex flex-row-reverse">
                                            <a href="{% url 'cart:cart_detail' %}" class="btn-lg" style="font-size:40px; color:black ">
                                                <span class="zmdi zmdi-shopping-cart"></span>
                                            </a>
                                        </div>

                                        <div style="margin-top:-70px; margin-left:35px">
                                            <a href="{% url 'cart:cart_detail' %}" class="badge badge-success">{{ total_items }}</a>
                                        </div>
<!--                                        {% if total_items == 0 %}-->
<!--                                            <div class="alert alert-danger">-->
<!--                                              <strong>Danger!</strong> You should <a href="#" class="alert-link">read this message</a>.-->
<!--                                            </div>-->
<!--                                        {% else %}-->

<!--                                        <div class="alert alert-success">-->
<!--                                              <strong>Success!</strong> Indicates a successful or positive action.-->
<!--                                            </div>-->
<!--                                        {% endif %}-->

                                    </a>
                                </div>
                                {% else %}
                                <div style=" height:50px; width:65px;">
                                    <a href="{% url 'cart:cart_detail' %}">
                                        <div class="d-flex flex-row-reverse">
                                            <a href="{% url 'cart:cart_detail' %}" class="btn-lg" style="font-size:40px; color:black ">
                                                <span class="zmdi zmdi-shopping-cart-plus"></span>
                                            </a>
                                        </div>
                                        <div style="margin-top:-77px; margin-left:40px">
                                            <a href="{% url 'cart:cart_detail' %}" class="badge badge-success">{{ total_items }}</a>
                                        </div>
                                    </a>
                                </div>
                                {% endif %}
                                {% endwith %}
                            </div>
                        </li>
                    </ul>
                </div>

                <form method='get' action="{% url 'shop:Search' %}" class="form-inline my-1 my-lg-0 ">
                    <input class="form-control mr-sm-2" name="search" id="search" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                 </form>
            </div>
        </div>

    </div>
    <div class="row my-3">
            <div class="col-lg-12">
                <div style="border-radius:5px; background-color:#F07E2B; height:5px">
                </div>
            </div>
        </div>




    <div style="overflow:hidden;position: relative;"  class="container">
        {% block content %}

        {% endblock %}
    </div>



    <!-- Footer -->
<footer class="page-footer font-small unique-color-dark" style="background-color:#1c2331;color:white">

  <div style="background-color:#6351ce;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic" href="{% url 'cart:cart_detail' %}" style="color:white">
              <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic" href="{% url 'cart:cart_detail' %}" style="color:white">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic" href="{% url 'cart:cart_detail' %}" style="color:white">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic" href="{% url 'cart:cart_detail' %}" style="color:white">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic" href="https://www.instagram.com/mr_bajju_sutharr/" style="color:white">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">The Furniture Shop</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Furnishing Your Life!</p>
          <p>Furnishing Your Dreams.</p>
          <p>Great Furniture. Better Prices.</p>
          <p>Furniture On A Budget.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">MDBootstrap</a>
        </p>
        <p>
          <a href="#!">MDWordPress</a>
        </p>
        <p>
          <a href="#!">BrandFlow</a>
        </p>
        <p>
          <a href="#!">Bootstrap Angular</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">Your Account</a>
        </p>
        <p>
          <a href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a href="#!">Shipping Rates</a>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Baroda, 390024, India.</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> your_tfs0@gmail.com </p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 91 8511148214</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 91 7096941400</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3" style="background-color:#161c27">© 2018 Copyright:
    <a href="https://www.instagram.com/mr_bajju_sutharr/"> Bajrang And Company</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>

</html>